[package]
name = "lib_shift_encryptor"
version = "0.1.0"
authors = ["Антон Панов <hightemp.unknown@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.5.0"