[package]
name = "lib_shift_encryptor"
version = "0.1.0"
authors = ["Антон Панов <hightemp.unknown@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byte_array = "0.1.3"
lazy_static = "0.2"